/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PraticaRouteImport } from './routes/pratica'
import { Route as ReferenciaRouteImport } from './routes/referencia'
import { Route as LicaoIdRouteImport } from './routes/licao.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticaRoute = PraticaRouteImport.update({
  id: '/pratica',
  path: '/pratica',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciaRoute = ReferenciaRouteImport.update({
  id: '/referencia',
  path: '/referencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LicaoIdRoute = LicaoIdRouteImport.update({
  id: '/licao/$id',
  path: '/licao/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pratica': typeof PraticaRoute
  '/referencia': typeof ReferenciaRoute
  '/licao/$id': typeof LicaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pratica': typeof PraticaRoute
  '/referencia': typeof ReferenciaRoute
  '/licao/$id': typeof LicaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pratica': typeof PraticaRoute
  '/referencia': typeof ReferenciaRoute
  '/licao/$id': typeof LicaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/pratica' | '/referencia' | '/licao/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/pratica' | '/referencia' | '/licao/$id'
  id: '__root__' | '/' | '/auth' | '/pratica' | '/referencia' | '/licao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PraticaRoute: typeof PraticaRoute
  ReferenciaRoute: typeof ReferenciaRoute
  LicaoIdRoute: typeof LicaoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratica': {
      id: '/pratica'
      path: '/pratica'
      fullPath: '/pratica'
      preLoaderRoute: typeof PraticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencia': {
      id: '/referencia'
      path: '/referencia'
      fullPath: '/referencia'
      preLoaderRoute: typeof ReferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licao/$id': {
      id: '/licao/$id'
      path: '/licao/$id'
      fullPath: '/licao/$id'
      preLoaderRoute: typeof LicaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PraticaRoute: PraticaRoute,
  ReferenciaRoute: ReferenciaRoute,
  LicaoIdRoute: LicaoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
